### ISSUE TITLE
VIF needs constant and target should be removed

### ISSUE THREAD

**Issue by ArneTR** [kennethleungty/Logistic-Regression-Assumptions#2]
Hi @kennethleungty ,

thank you for the great notebook.

I just worked through the Python Notebook and think the VIF calculation may not be done against the target variable.

1. Since you just want to figure out the mutlicolinearity of the covariates the target must be removed.

2. Also to my knowledge the VIF must include an intercept. The python implementation of the function "variance_inflation_factor" does not add this by itself. So a call to sm.add_constant() must be done to the dataframe beforehand.

For #1 I have no specific source, but just remember this from my statistic lecture.
For #2 I have the following sources:
- https://stackoverflow.com/questions/42658379/variance-inflation-factor-in-python
- The R-Package car with the vif() function also includes an intercept: https://www.statology.org/variance-inflation-factor-r/
=> Using the python function to recalculate the package only gives the same result if the intercept is inlucded.

- I also include a controversial source, as here a comment says, that there is a debate wether to include Intercept or not. I found no other source of that though and R seems to default otherwise: https://stackoverflow.com/questions/59694427/what-does-the-high-vif-for-the-constant-term-intercept-indicate

Compare:
```
import statsmodels.api as sm
import pandas as pd
from statsmodels.stats.outliers_influence import variance_inflation_factor

mtcars = sm.datasets.get_rdataset("mtcars", "datasets", cache=True).data
df_raw = pd.DataFrame(mtcars)
df = df_raw.loc[:, ['disp', 'hp', 'wt', 'drat']]

## Without intercept
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(df.values, i) for i in range(df.shape[1])]
vif["features"] = df.columns
vif

## With intercept
df_const = sm.add_constant(df, prepend = False)
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(df_const.values, i) for i in range(df_const.shape[1])]
vif["features"] = df_const.columns
vif
```

Another and more readable way, that is even more similar to R would be to use formulas:
```
from patsy import dmatrices
y, X = dmatrices('mpg ~ disp + hp + wt + drat', data=df_raw, return_type='dataframe')
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif["features"] = X.columns
vif
```

Looking forward to your feedback.

**Comment by kennethleungty** [comment]
Hi @ArneTR,

Thanks for the analysis and information! I have looked through them and agree with what you have brought up. Indeed the VIF calculation should include the constant. As for the multicollinearity matrix, while I feel the target variable does not affect the correlation values across the heatmap, I do agree that removing the target will make the matrix more interpretable, and places the focus rightly on multicollinearity amongst the predictor variables.

Really appreciate your efforts in raising them up! I have added your name into the Special Thanks section of the README, and have also made the relevant changes to the notebook and article to reflect this issue.
